name: dayly
description: A smart planner in the form of a mobile app.  

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # IOS Stylings
  cupertino_icons: ^0.1.3

  # Firebase
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.15
  firebase_helpers: ^0.1.9
  firebase_messaging: ^6.0.16
  
  # Streams
  rxdart: ^0.24.1
  
  # Google
  googleapis: ^0.55.0
  google_sign_in: ^4.5.1

  # Provider
  provider: ^4.1.2

  # UI Related
  flutter_svg: ^0.17.4
  flutter_spinkit: "^4.1.2"
  curved_navigation_bar: ^0.3.2
  image_picker: ^0.6.7+1
  google_fonts: ^1.1.0
  percent_indicator: ^2.1.5
  circular_check_box: ^1.0.2
  numberpicker: ^1.2.0
  timeline_tile: ^0.1.2
  modal_bottom_sheet: ^0.2.0+1
  flutter_material_pickers: ^1.6.0
#  reorderables:
#  implicitly_animated_reorderable_list: ^0.2.3
#  flutter_reorderable_list: ^0.1.4

  # Validations
  email_validator: ^1.0.4

  # Utilities
  uuid: ^2.1.0
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  device_preview: ^0.4.7
  device_info: ^0.4.2+4
  http: ^0.12.2

  # Notifications
  flutter_local_notifications: ^1.4.4+2
  
  # Calendar\
  syncfusion_flutter_calendar: 18.1.59-beta
  



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Regular.ttf
    - family: Falling
      fonts:
        - asset: fonts/fallingsky.otf
        - asset: fonts/fallingskybold.otf
          weight: 700
